### ISSUE TITLE
VoIP call

### ISSUE THREAD

**Issue by NarHakobyan** [voximplant/flutter_callkit#3]
Hi, thanks for good lib, I need help with voip and incoming call, where am I need to put didDisplayIncomingCall function to receive call when app is closed? I checked example but didn't found anything related to that

**Comment by VladimirBrejcha** [comment]
Hi,

didDisplayIncomingCall is fired immediately after CallKit processes a push from the native code and opens its UI with an incoming call.
So In the dart code you should to set this callback as early as possible (because it will be called very soon after app start)

About receiving a call when the app is closed:
1. You'll need voip pushes set up
2. You'll need to notify callKit in iOS native code about incoming call as showed in the [readme](https://github.com/voximplant/flutter_callkit#swift)
3. CallKit UI will be showed up
4. didDisplayIncomingCall will be called in dart code

**Comment by NarHakobyan** [comment]
Thanks for the fast reply, am I need to set it before run() function?

**Comment by VladimirBrejcha** [comment]
It might work if you set it later, but not guaranteed, so if it is possible to set this callback before runApp() - do it.

about the second question: correct, this will show callKit UI
