### ISSUE TITLE
Feature request: Android SDK implementation

### ISSUE THREAD

**Issue by shree675** [voximplant/flutter_callkit#32]
This is a really useful package and would greatly help me in my current flutter project. But unfortunately, I need this for android devices. I would really appreciate it if this is made for android SDK as well since a lot of other people may also benefit.

**Comment by YuliaGrigorieva** [comment]
Hello! Thank you for your feature request!

Unfortunately, we do not plan to add Android support to this plugin. The reason for that is that CallKit is the Apple specific framework, it’s available only on Apple devices (iOS, iPad OS, Mac OS). 

Android platform has a similar (but not the same) functionality that can be implemented via a self managed ConnectionService.

Our goal is to create the plugins with the closest API to native API to give the developers all functionality and flexibility the native API provide. Since the Android ConnectionService API is different from Apple CallKit, we can't align Apple API with the Android one. 

According to our vision for Flutter plugins, we think that Android ConnectionService should be a separate plugin. I have added your request to our backlog, so we will analyze the ways how it could be implemented. However, I can't provide any estimates now.

Best regards,
Yulia Grigorieva
